import full from './data/doomsday-prep.js'; import essentials from './data/doomsday-essential.js'; import {mediaLibrary} from './data/media.js'; import {seriesLibrary} from './data/series.js';
const playlists=[full,essentials], $=id=>document.getElementById(id), KEY='doomsday-watch-progress-v1', DAY=86400000;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}} function save(p){localStorage.setItem(KEY,JSON.stringify(p))}
function pid(i){return i.displayType==='episode'?`episode:${i.ref}:s${i.season}:e${i.episode}`:i.displayType==='special'?`special:${i.id||i.ref}`:`movie:${i.ref}`}
function watched(i,p=load()){return p[pid(i)]?.watched===true||p[pid(i)]===true} function setWatched(i,v){const p=load(); if(v)p[pid(i)]={watched:true,watchedAt:new Date().toISOString()};else delete p[pid(i)];save(p)}
function media(ref){return mediaLibrary.find(x=>x.id===ref)||{id:ref,title:ref.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase()),poster:''}}
function specialLabel(i){const r=(i.ref||'').toLowerCase(); if(r.includes('mid-credit'))return'Mid-Credit Scene';if(r.includes('post-credit'))return'Post-Credit Scene';if(r.includes('all-credit'))return'All Credits';if(r.endsWith('credits'))return'Credits';return'Credit Scene'}
function expand(pl){const out=[];(pl.items||[]).forEach(i=>{let m=media(i.ref), shared={...m,...i,title:i.title||m.title,poster:i.poster||m.poster||''};if(i.type==='special'){shared.displayType='special';shared.specialLabel=specialLabel(i);out.push(shared);return}if(i.type==='episode-list'){(i.episodes||[]).forEach(e=>out.push({...shared,displayType:'episode',season:e.season,episode:e.episode,episodeTitle:e.title||''}));return}if(i.type==='season'){const s=seriesLibrary.find(x=>x.id===i.ref),sd=s?.seasons?.find(x=>+x.season===+i.season),eps=sd?.episodes||[];if(eps.length)eps.forEach(e=>out.push({...shared,displayType:'episode',season:i.season,episode:e.episode,episodeTitle:e.title||''}));else for(let e=1;e<=+(i.episodeCount||0);e++)out.push({...shared,displayType:'episode',season:i.season,episode:e,episodeTitle:''});return}out.push({...shared,displayType:i.type||m.mediaType||'movie'})});return out}
function state(items){const p=load(), ws=items.map(i=>watched(i,p)), count=ws.filter(Boolean).length, idx=ws.findIndex(x=>!x);return{ws,count,remaining:items.length-count,idx:idx<0?items.length:idx,current:idx<0?null:items[idx]}}
function label(i){if(i.displayType==='episode')return`S${i.season} E${i.episode}${i.episodeTitle?' — '+i.episodeTitle:''}`;if(i.displayType==='special')return i.note||'Specially placed credit scene';return [i.year||'Movie',i.priority].filter(Boolean).join(' · ')}
function eventData(pl,items,done){if(!pl.event?.date)return null;const ev=new Date(pl.event.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);const days=Math.ceil((ev-now)/DAY),remain=items.length-done,weeks=Math.max(days/7,1/7),goal=remain?Math.ceil(remain/weeks):0,pct=items.length?Math.round(done/items.length*100):0;let status=remain===0?'Complete':days<0?'Target Passed':goal<=2?'Comfortably On Track':goal<=5?'On Track':goal<=8?'Pick Up the Pace':'Marathon Mode';const p=load(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()-1+7)%7));const next=new Date(monday);next.setDate(monday.getDate()+7);const thisWeek=items.filter(i=>{const d=p[pid(i)]?.watchedAt?new Date(p[pid(i)].watchedAt):null;return d&&d>=monday&&d<next}).length;return{ev,days,remain,goal,pct,status,thisWeek}}
function countdown(e){if(e.remain===0)return'Ready for Doomsday';if(e.days===0)return'Doomsday is today';if(e.days<0)return`${Math.abs(e.days)} days past target`;return`${e.days} days remaining`}
function eventCard(e){if(!e)return'';return`<section class="event-card"><div class="event-head"><div><p class="eyebrow">Avengers: Doomsday</p><h2>${esc(countdown(e))}</h2><p>${e.ev.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</p></div><div class="countdown"><strong>${e.days>0?e.days:0}</strong><span>days</span></div></div><div class="progress-copy"><span>Overall progress</span><strong>${e.pct}%</strong></div><div class="progress-track"><span style="width:${e.pct}%"></span></div><div class="event-stats"><div><span>Remaining</span><strong>${e.remain}</strong></div><div><span>Weekly target</span><strong>${e.goal}</strong><small>${e.thisWeek} watched this week</small></div><div><span>Pace</span><strong>${esc(e.status)}</strong></div></div></section>`}
function renderHome(){const grid=$('playlistGrid');grid.innerHTML='';playlists.forEach(pl=>{const items=expand(pl),s=state(items),e=eventData(pl,items,s.count),b=document.createElement('button');b.className='playlist-card';b.innerHTML=`<div class="card-art"><img src="${esc(pl.poster)}" alt=""><span></span><b>${items.length} items</b></div><div class="card-copy"><p class="eyebrow">Doomsday Prep</p><h2>${esc(pl.title.replace('Avengers: ',''))}</h2><p>${esc(pl.description)}</p><div class="card-progress"><span>${s.count} watched · ${s.remaining} remaining</span><strong>${e?esc(countdown(e)):''}</strong></div>${s.current?`<div class="up-mini">Up next: <strong>${esc(s.current.title)}</strong></div>`:''}</div>`;b.onclick=()=>showDetail(pl);grid.appendChild(b)})}
function showDetail(pl){$('homeView').classList.remove('active');$('detailView').classList.add('active');renderDetail(pl);scrollTo(0,0)}
function renderDetail(pl){const items=expand(pl),s=state(items),e=eventData(pl,items,s.count);let prev='';const rows=items.map((i,n)=>{let h='';if(i.section!==prev){prev=i.section;h=`<li class="section-heading"><span>${esc(i.section)}</span></li>`}return h+`<li class="playlist-item ${s.ws[n]?'watched':n===s.idx?'current':''} ${i.displayType==='special'?'special':''}" data-i="${n}" tabindex="0"><span class="status">${s.ws[n]?'✓':n===s.idx?'▶':n+1}</span>${i.poster?`<img src="${esc(i.poster)}" alt="" loading="lazy">`:''}<div><strong>${esc(i.title)}</strong>${i.displayType==='special'?`<span class="special-label">🎬 ${esc(i.specialLabel)}</span>`:''}<span>${esc(label(i))}</span></div></li>`}).join('');$('playlistDetail').innerHTML=`<article class="detail"><button id="back" class="back">← Back to Watchlists</button><header><p class="eyebrow">Doomsday Watchlist</p><h1>${esc(pl.title)}</h1><p>${esc(pl.description)}</p><div class="summary"><span>${s.count} watched</span><span>${s.remaining} remaining</span></div></header>${s.current?`<section class="up-next"><div><p class="eyebrow">Up Next</p><div class="up-main">${s.current.poster?`<img src="${esc(s.current.poster)}" alt="">`:''}<div><h2>${esc(s.current.title)}</h2><p>${esc(label(s.current))}</p></div></div></div><button id="mark">Mark Watched</button></section>`:`<section class="up-next"><div><p class="eyebrow">Playlist Complete</p><h2>Ready for Avengers: Doomsday</h2></div></section>`}${eventCard(e)}<ol class="item-list">${rows}</ol><section class="reset-zone"><div><strong>Reset Playlist Progress</strong><span>Clears watched progress for every item in this watchlist. Shared entries also update in the other Doomsday watchlist.</span></div><button id="reset">Reset Playlist</button></section></article>`;$('back').onclick=()=>{closeSheet();$('detailView').classList.remove('active');$('homeView').classList.add('active');renderHome();scrollTo(0,0)};if($('mark'))$('mark').onclick=()=>{setWatched(s.current,true);renderDetail(pl)};$('reset').onclick=()=>{if(confirm('Reset all progress for this watchlist?')){items.forEach(i=>setWatched(i,false));renderDetail(pl)}};document.querySelectorAll('.playlist-item[data-i]').forEach(row=>{let t;const i=items[+row.dataset.i];const open=()=>openSheet(i,watched(i),()=>renderDetail(pl));row.oncontextmenu=x=>{x.preventDefault();open()};row.onpointerdown=x=>{if(x.pointerType==='mouse'&&x.button!==0)return;t=setTimeout(open,600)};['onpointerup','onpointercancel','onpointerleave'].forEach(k=>row[k]=()=>clearTimeout(t));row.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();open()}}})}
function closeSheet(){document.querySelector('.sheet-bg')?.remove()} function openSheet(i,isW,rerender){closeSheet();const bg=document.createElement('div');bg.className='sheet-bg';bg.innerHTML=`<div class="sheet"><i></i><p class="eyebrow">Watchlist Item</p><h2>${esc(i.title)}</h2><p>${esc(label(i))}</p><button id="toggle">${isW?'Mark Unwatched':'Mark Watched'}</button><button id="cancel" class="secondary">Cancel</button></div>`;document.body.appendChild(bg);bg.onclick=x=>{if(x.target===bg)closeSheet()};bg.querySelector('#cancel').onclick=closeSheet;bg.querySelector('#toggle').onclick=()=>{setWatched(i,!isW);closeSheet();rerender()}}
$('homeButton').onclick=()=>{$('detailView').classList.remove('active');$('homeView').classList.add('active');renderHome()};$('refreshButton').onclick=()=>location.reload();renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
